### ISSUE TITLE
FYI: Regarding CWA: Signature checks will be added in version 2.7

### ISSUE THREAD

**Issue by Ein-Tim** [stealth/greenday#2]
See: https://github.com/corona-warn-app/cwa-app-android/pull/3779 & https://github.com/corona-warn-app/cwa-app-ios/pull/3194

**Comment by stealth** [comment]
Nice.

**Comment by Ein-Tim** [comment]
@stealth Will you update your text in any way to reflect the added signature checks in version 2.7?

**Comment by stealth** [comment]
Sure
